function [CTORQUE1, CTORQUE2, CTORQUE3, IB11, IB12, IB22, IB23,IB31 ,IB33, IRW1, IRW2, IRW3, MASSB, EP1, EP2, EP3, EP4, Q1, Q2, Q3, U1, U2, U3, U4, U5, U6, U7, U8, U9, TINITIAL, TFINAL, INTEGSTP, PRINTINT, ABSERR, RELERR] = getInputs(Fname)
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: The input variable Fname
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 22-Sep-2020 22:17:47

%% Setup the Import Options and import the data
%global Fname
opts = spreadsheetImportOptions("NumVariables", 35);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:AI2";

% Specify column names and types
opts.VariableNames = ["CTORQUE1", "CTORQUE2", "CTORQUE3", "IB11", "IB12", "IB22", "IB23","IB31", "IB33", "IRW1", "IRW2", "IRW3", "MASSB", "EP1", "EP2", "EP3", "EP4", "Q1", "Q2", "Q3", "U1", "U2", "U3", "U4", "U5", "U6", "U7", "U8", "U9", "TINITIAL", "TFINAL", "INTEGSTP", "PRINTINT", "ABSERR", "RELERR"];
opts.VariableTypes = ["double", "double", "double", "double", "double","double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data

%pause(5000)
tbl = readtable(Fname, opts, "UseExcel", false);

%% Convert to output type
CTORQUE1 = tbl.CTORQUE1;
CTORQUE2 = tbl.CTORQUE2;
CTORQUE3 = tbl.CTORQUE3;
IB11 = tbl.IB11;
IB12 = tbl.IB12;
IB22 = tbl.IB22;
IB23 = tbl.IB23;
IB31 = tbl.IB31;
IB33 = tbl.IB33;
IRW1 = tbl.IRW1;
IRW2 = tbl.IRW2;
IRW3 = tbl.IRW3;
MASSB = tbl.MASSB;
EP1 = tbl.EP1;
EP2 = tbl.EP2;
EP3 = tbl.EP3;
EP4 = tbl.EP4;
Q1 = tbl.Q1;
Q2 = tbl.Q2;
Q3 = tbl.Q3;
U1 = tbl.U1;
U2 = tbl.U2;
U3 = tbl.U3;
U4 = tbl.U4;
U5 = tbl.U5;
U6 = tbl.U6;
U7 = tbl.U7;
U8 = tbl.U8;
U9 = tbl.U9;
TINITIAL = tbl.TINITIAL;
TFINAL = tbl.TFINAL;
INTEGSTP = tbl.INTEGSTP;
PRINTINT = tbl.PRINTINT;
ABSERR = tbl.ABSERR;
RELERR = tbl.RELERR;

%% Clear temporary variables
clear opts tbl